name: football_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  stacked: ^3.1.1
  stacked_services: ^0.9.9
  get_it: 7.2.0
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: any
  stacked_generator: any
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:

  uses-material-design: true

  assets:
    - .env